import React from "react";
import { useWeather } from "../hooks/useWeatherQueries";

// Layout & Reusable Container Components
import { PageContainer } from "../components/common/PageContainer";
import { ErrorState } from "../components/common/ErrorState";
import {
  HeroSkeleton,
  StatsSkeleton,
  HourlySkeleton,
  CardSkeleton
} from "../components/common/Skeletons";

// Weather-Specific Cards
import HeroWeatherCard from "../components/weather/HeroWeatherCard";
import CurrentWeather from "../components/weather/CurrentWeather";
import ForecastCards from "../components/weather/ForecastCards";
import HourlyForecast from "../components/weather/HourlyForecast";
import DailyForecast from "../components/weather/DailyForecast";
import WeatherStatistics from "../components/weather/WeatherStatistics";
import Wind from "../components/weather/Wind";
import Temperature from "../components/weather/Temperature";
import LocationCard from "../components/weather/LocationCard";
import WeatherSummary from "../components/weather/WeatherSummary";
import WeatherIntelligence from "../components/weather/WeatherIntelligence";


export default function WeatherDashboard() {
  const { data: weatherData, isLoading, isError, refetch } = useWeather();

  // 1. Loading State Skeletons
  if (isLoading) {
    return (
      <PageContainer
        title="Weather Intelligence Dashboard"
        description="Synchronizing spatial metrics and atmospheric predictions..."
      >
        <div className="space-y-6 sm:space-y-8">
          <HeroSkeleton />
          <StatsSkeleton />
          <div className="grid grid-cols-12 gap-6">
            <div className="col-span-12 lg:col-span-8 space-y-6">
              <HourlySkeleton />
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <CardSkeleton className="h-96" />
                <CardSkeleton className="h-96" />
              </div>
            </div>
            <div className="col-span-12 lg:col-span-4 space-y-6">
              <CardSkeleton className="h-44" />
              <CardSkeleton className="h-44" />
              <CardSkeleton className="h-44" />
            </div>
          </div>
        </div>
      </PageContainer>
    );
  }

  // 2. Error State UI
  if (isError || !weatherData) {
    return (
      <PageContainer
        title="Weather Intelligence Dashboard"
        description="Atmospheric telemetry sync error"
      >
        <div className="py-12">
          <ErrorState
            title="Unable to sync weather telemetries"
            message="We couldn't connect to the Weather AI service. Please check your internet connection, API key configuration, or click Retry below."
            onRetry={refetch}
          />
        </div>
      </PageContainer>
    );
  }

  // 3. Main Dashboard UI
  return (
    <PageContainer
      title="Weather Intelligence"
      description="Real-time atmospheric analysis, microclimate alerts, and predictive scheduling insights"
    >
      <div className="space-y-6 sm:space-y-8">
        {/* Row 1: Hero Landing Block */}
        <HeroWeatherCard weatherData={weatherData} />

        {/* Row 2: Secondary Current Metrics Grid */}
        <CurrentWeather weatherData={weatherData} />

        {/* Row 3: Autogenerated Forecast Alerts and Highlights */}
        <ForecastCards weatherData={weatherData} />

        {/* Row 3.5: Actionable Intelligence recommendations */}
        <WeatherIntelligence weatherData={weatherData} />


        {/* Row 4: Complex Multi-column Layout */}
        <div className="grid grid-cols-12 gap-6 items-start">
          {/* Main Forecast Insights (Left/Top) */}
          <div className="col-span-12 lg:col-span-8 space-y-6">
            <HourlyForecast weatherData={weatherData} />
            
            <div className="grid grid-cols-12 gap-6">
              <DailyForecast weatherData={weatherData} />
              <WeatherStatistics weatherData={weatherData} />
            </div>
          </div>

          {/* Secondary Analytics Widgets (Right/Bottom) */}
          <div className="col-span-12 lg:col-span-4 space-y-6">
            <Wind weatherData={weatherData} />
            <Temperature weatherData={weatherData} />
            <LocationCard weatherData={weatherData} />
            <WeatherSummary weatherData={weatherData} />
          </div>
        </div>
      </div>
    </PageContainer>
  );
}
